name: Android CI

on:
  pull_request:
    branches:
      - 'research/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Add chmod to gradlew
      run: chmod +x ./gradlew
      
    - name: Build APK with Gradle
      run: ./gradlew assembleDebug

    - name: Upload App Distribution with Gradle
      run: ./gradlew appDistributionUploadDebug
      env:
        FIREBASE_TOKEN: 1//0g4W1Bb8gA398CgYIARAAGBASNwF-L9Irzp-8MnXjRsmp1t7G8-Z3BmUOIFtvnPXD_zUiTRNWExMTaCzMjuWluoJZZ8jhqRGAopA

#test changes